### ISSUE TITLE
Can't start sclang in tmux

### ISSUE THREAD

**Issue by sjomae** [davidgranstrom/scnvim-tmux#4]
Works fine outside tmux.

But when running, :SCNvimStart inside tmux it fails

![scnvim-tmux-start-fails](https://github.com/davidgranstrom/scnvim-tmux/assets/128092741/33662065-4f70-4b52-b0b0-40926b93e789)

`lua << EOF
require('scnvim').setup()
EOF

lua << EOF
local scnvim = require 'scnvim'
local map = scnvim.map
local map_expr = scnvim.map_expr
scnvim.setup ({

ensure_installed = true,
  sclang = {
    cmd = nil,
    args = {},
  },
  keymaps = {},
  documentation = {
    cmd = nil,
    horizontal = true,
    direction = 'top',
    keymaps = true,
  },
  postwin = {
    highlight = true,
    auto_toggle_error = true,
    scrollback = 5000,
    horizontal = false,
    direction = 'right',
    size = nil,
    fixed_size = nil,
    keymaps = nil,
    float = {
      enabled = false,
      row = 0,
      col = function()
        return vim.o.columns
      end,
      width = 64,
      height = 14,
      config = {
        border = 'single',
      },
      callback = function(id)
        vim.api.nvim_win_set_option(id, 'winblend', 10)
      end,
    },
  },
  editor = {
    force_ft_supercollider = true,
    highlight = {
      color = 'TermCursor',
      type = 'flash',
      flash = {
        duration = 100,
        repeats = 2,
      },
      fade = {
        duration = 375,
      },
    },
    signature = {
      float = true,
      auto = true,
    },
  },
  snippet = {
    engine = {
      name = 'luasnip',
      options = {
        descriptions = true,
      },
    },
  },
  statusline = {
    poll_interval = 1,
  },
  extensions = {
      tmux = {
      cmd = 'less',
      args = { '-S', '+F', '$1' },
    },
  },
})

scnvim.load_extension 'tmux'
-- scnvim.load_extension('piano')
EOF
`

**Comment by sjomae** [comment]
Sometimes it works just fine. It looks like it has something to do with whether a other tmux session is open or not... will explore further.

**Comment by sjomae** [comment]
Probably related:
https://github.com/davidgranstrom/scnvim-tmux/issues/3

**Comment by davidgranstrom** [comment]
@sjomae Thanks for the report. I've personally moved away from using `tmux` (for the moment at least) after being a long time user. Not sure when I will have time to investigate this issue further, but I would be open to PR if you find out what might be causing this.

**Comment by sjomae** [comment]
More a quick note (for myself), could be related maybe (wild shot). 

Before tmux 2.2, tmux accepted input from STDIN. This doesn't work anymore.

source: https://github.com/jpalardy/vim-slime

**Comment by sjomae** [comment]
Seems fixed by https://github.com/davidgranstrom/scnvim-tmux/issues/3

Thanks @rumblesan
